blank_issues_enabled: false
contact_links:
  - name: Ask a question / support
    url: https://github.com/selgebali/datacite4.6-jsonld/discussions
    about: Use Discussions for Q&A and general support threads.
