name: Validation / Schema bug
description: Something is wrong with the profile, rules, enums, context, or validator.
title: "[BUG] <short summary>"
labels: [bug, validation]
assignees: []
body:
  - type: checkboxes
    id: scope
    attributes:
      label: Affected area(s)
      options:
        - label: datacite4.6-profile.json
        - label: rules.json
        - label: enum_lists/*
        - label: main_context.jsonld
        - label: scripts/make_datacite_context.py
        - label: validate.js / validation pipeline
        - label: skos-mappings/*
  - type: input
    id: ref
    attributes:
      label: Commit / tag
      description: Commit SHA or tag where you observed the issue.
      placeholder: e.g., 2f13ab7 or v0.4.1
  - type: textarea
    id: summary
    attributes:
      label: What happened?
      description: Brief description of the bug.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: CLI steps or actions to reproduce.
      placeholder: |
        1. Run `node validate.js datacite_example_filledin.json`
        2. See error ...
    validations:
      required: true
  - type: textarea
    id: input
    attributes:
      label: Minimal JSON example
      description: Smallest possible JSON that triggers the problem.
      render: json
      placeholder: |
        {
          "types": { "resourceTypeGeneral": "Dataset" },
          "creators": [ ... ]
        }
  - type: textarea
    id: expected
    attributes:
      label: Expected vs actual
      description: What should happen vs what actually happens.
      placeholder: "Expected: passes rule X. Actual: fails with message Y."
  - type: textarea
    id: logs
    attributes:
      label: Validator output / stacktrace
      render: shell
  - type: dropdown
    id: severity
    attributes:
      label: Impact
      options:
        - Blocks submission
        - Incorrect validation (false positive/negative)
        - Minor / cosmetic
  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission checks
      options:
        - label: I verified on the latest main branch.
        - label: I can help test a fix.
